### ISSUE TITLE
Basic calendar view for navigating audio recordings

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-client#143]
There is already a [basic implementation of this in baw-server](https://github.com/QutBioacoustics/baw-server/blob/develop/app/views/public/audio_recording_catalogue.html.haml)

This depends on the audio_recordings endpoint in baw-server implementing Filtering in the [Rails API spec](https://github.com/QutBioacoustics/baw-server/wiki/Rails-API-Spec)

**Comment by atruskie** [comment]
This is implemented as the visualisation page, tracked here: https://github.com/QutBioacoustics/baw-client/pull/172
