### ISSUE TITLE
Upgrade to angular 1.4

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-client#171]
1.4 is not released yet, however 1.3+ builds are currently blocked by a dependency not supporting 1.3+.

relevant bower output:

```
Please note that,
    angular-tags#b862d92845 depends on angular#1.2.0-rc.1 which resolved to angular#1.2.0-rc.1
    angular-bootstrap#0.12.0 depends on angular#>=1 <1.3.0 which resolved to angular#1.2.28
    angular-mocks#1.3.1 depends on angular#1.3.1 which resolved to angular#1.3.1
    baw-client depends on angular#1.3.x which resolved to angular#1.3.10
    angular-ui-utils#0.1.1 depends on angular#>= 1.0.2 which resolved to angular#1.3.10
    angular-growl-v2#0.7.0 depends on angular#>=1.2.1 which resolved to angular#1.3.10
    angular-ui-bootstrap-bower#0.6.0 depends on angular#>=1 which resolved to angular#1.3.10
Resort to using angular#1.3.x which resolved to angular#1.3.1
Code incompatibilities may occur.

bower angular#1.3.1            install angular#1.3.1
```

**Comment by cofiem** [comment]
Looks like the problematic dependencies are:

 - angular-tags#b862d92845 depends on angular#1.2.0-rc.1 which resolved to angular#1.2.0-rc.1
   - that project is inactive: https://github.com/boneskull/angular-tags
   - this seems more active: https://github.com/mbenford/ngTagsInput
 - angular-bootstrap#0.12.0 depends on angular#>=1 <1.3.0 which resolved to angular#1.2.28
 -  angular-mocks#1.3.1 depends on angular#1.3.1 which resolved to angular#1.3.1

These seem fine (for 1.3.10):

 - angular-ui-utils#0.1.1 depends on angular#>= 1.0.2 which resolved to angular#1.3.10
 - angular-growl-v2#0.7.0 depends on angular#>=1.2.1 which resolved to angular#1.3.10
 - angular-ui-bootstrap-bower#0.6.0 depends on angular#>=1 which resolved to angular#1.3.10
