### ISSUE TITLE
Audio player does not work in IE

### ISSUE THREAD

**Issue by alvinsw** [QutBioacoustics/baw-client#174]
The audio player does not work even in IE 11.
It does not load the audio and the play button is greyed out.

**Comment by atruskie** [comment]
Even in IE 11?

It should be compatible with IE 10.

There's a variety of reasons you may see this bug - have you attempted to diagnose the issue?
Typically we need more information/context to diagnose an issue like this. What does the console say?

Well it
![It  works on my machine](http://blogs.msdn.com/blogfiles/pranavwagh/WindowsLiveWriter/WhatsWorksonMyMachineCertificationProgra_AAB/works-on-my-machine-starburst_2.png)

http://gyazo.com/2529cd0b0e3a6cc39b3f076703df4f47

**Comment by alvinsw** [comment]
Can you confirm that you can playback a recording from ecosounds in IE 11 on your machine, for example: http://baw.ecosounds.org/listen/244368
Because I tried that one in IE 11 (Edge) and it does not play. It shows everything visually including the spectrogram and the tagging, but it just won't play.
Several people that trialled the baw.dev.bush.fm also reported that it does not work (including a Mac user). I am guessing that they used IE.

**Comment by atruskie** [comment]
A Mac user was using IE? That doesn't sound right.

Again it (http://baw.ecosounds.org/listen/244368) works on my machine.

What does the console say?

**Comment by alvinsw** [comment]
There are quite a lot of messages there:

HTML1300: Navigation occurred.
File: 244368
SCRIPT16389: Unspecified error.
File: 244368, Line: 1, Column: 1
Creating module  bawApp.vendorServices.auto
Creating provider  moment
Creating provider  lodash
Creating provider  d3
Creating provider  bowser
Creating provider  humanize-duration
cleaning up vendor externals hack
No temporary CSRF token has been found!
No temporary CSRF token has been found!
No temporary CSRF token has been found!
No temporary CSRF token has been found!
No temporary CSRF token has been found!
decipher.tags.initialized [object Arguments]
   "decipher.tags.initialized"
   {
      [functions]: ,
      0: { },
      1: { },
      __proto__: { },
      callee: <Permission denied>,
      caller: <Permission denied>,
      length: 2
   }

No temporary CSRF token has been found!
No temporary CSRF token has been found!
No temporary CSRF token has been found!
No temporary CSRF token has been found!
No temporary CSRF token has been found!
No temporary CSRF token has been found!
No temporary CSRF token has been found!
controller function 12
link function: 12
transclude function: [object Arguments]
   "transclude function:"
   {
      [functions]: ,
      0: { },
      1: { },
      __proto__: { },
      callee: <Permission denied>,
      caller: <Permission denied>,
      length: 2
   }

switch state:link function: 12 [object Arguments]
   "switch state:link function:"
   12
   {
      [functions]: ,
      0: { },
      1: { },
      2: { },
      3: undefined,
      4: null,
      __proto__: { },
      callee: <Permission denied>,
      caller: <Permission denied>,
      length: 5
   }

switch state:link function: 12 [object Arguments]
   "switch state:link function:"
   12
   {
      [functions]: ,
      0: { },
      1: { },
      2: { },
      3: undefined,
      4: null,
      __proto__: { },
      callee: <Permission denied>,
      caller: <Permission denied>,
      length: 5
   }

No temporary CSRF token has been found!
AnnotationEditor:watchForSpectrogramChanges:updateUnitConverters: update cancelled, newValue is falsey
AnnotationEditor:modelCollectionUpdated:  
   "AnnotationEditor:modelCollectionUpdated:"
   [
      length: 0
   ]
   [
      length: 0
   ]

No temporary CSRF token has been found!
ngAudio:audioElement:eventType:  emptied 0
ngAudio:audioElement:eventType:  volumechange 0
Logged in via ping (probably used cookies).
Login successful [object Object]
   "Login successful"
   {
      [functions]: ,
      __proto__: { },
      authToken: "pN7p2GzgT3-72-y9zCX8",
      userName: "alvin.sebastian"
   }

authService::event:auth-loginConfirmed
User profile loaded
User profile hook success, retrieving app bookmarks [object Arguments]
   "User profile hook success, retrieving app bookmarks"
   {
      [functions]: ,
      0: { },
      __proto__: { },
      callee: <Permission denied>,
      caller: <Permission denied>,
      length: 1
   }

No temporary CSRF token has been found!
updatePreferences: throttled
updatePreferences: sending to server, waited 1 attempts
No temporary CSRF token has been found!
ngAudio:audioElement:eventType:  volumechange 0
updatePreferences: throttled
updatePreferences: sending to server, waited 1 attempts
No temporary CSRF token has been found!
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period).
AnnotationEditor:watchForSpectrogramChanges:updateUnitConverters
ngAudio:audioElement:eventType:  emptied 0
ngAudio:audioElement:eventType:  loadstart 0
ngAudio:audioElement:errorEvent [object Event]
   "ngAudio:audioElement:errorEvent"
   {
      [functions]: ,
      __proto__: { },
      AT_TARGET: 2,
      bubbles: false,
      BUBBLING_PHASE: 3,
      cancelable: false,
      cancelBubble: false,
      CAPTURING_PHASE: 1,
      constructor: { },
      currentTarget: { },
      defaultPrevented: false,
      eventPhase: 2,
      isTrusted: true,
      srcElement: { },
      target: { },
      timeStamp: 1424149224838,
      type: "error"
   }

ngAudio:audioElement:eventType:  error 0
Application bookmarks received [object Object]
   "Application bookmarks received"
   {
      [functions]: ,
      $promise: { },
      $resolved: true,
      __proto__: { },
      data: [ ],
      meta: { }
   }

Updating bookmark [object Object]
   "Updating bookmark"
   {
      [functions]: ,
      __proto__: { },
      audioRecordingId: 244368,
      category: "<<application>>",
      creatorId: 217,
      description: null,
      id: 8,
      name: "Last playback position",
      offsetSeconds: 0
   }

No temporary CSRF token has been found!
updatePreferences:failed [object Object]
   "updatePreferences:failed"
   {
      [functions]: ,
      __proto__: { },
      config: { },
      data: { },
      status: 422,
      statusText: "Unprocessable Entity"
   }

Bookmark save success
AnnotationEditor:watchForSpectrogramChanges:updateUnitConverters: update cancelled, newValue is falsey
No temporary CSRF token has been found!
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
AnnotationEditor:modelCollectionUpdated: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object] 
   "AnnotationEditor:modelCollectionUpdated:"
   [
      0: { },
      1: { },
      2: { },
      3: { },
      4: { },
      5: { },
      length: 6
   ]
   [
      length: 0
   ]

AnnotationEditor:modelUpdated: 141699 false
AnnotationEditor:modelUpdatesDrawabox: 141699
AnnotationEditor:modelUpdated: 149356 false
AnnotationEditor:modelUpdatesDrawabox: 149356
AnnotationEditor:modelUpdated: 149357 false
AnnotationEditor:modelUpdatesDrawabox: 149357
AnnotationEditor:modelUpdated: 149358 false
AnnotationEditor:modelUpdatesDrawabox: 149358
AnnotationEditor:modelUpdated: 149359 false
AnnotationEditor:modelUpdatesDrawabox: 149359
AnnotationEditor:modelUpdated: 149360 false
AnnotationEditor:modelUpdatesDrawabox: 149360
It would seem https://github.com/QutBioacoustics/baw-server/issues/135 has been fixed, remove me
No temporary CSRF token has been found!
updatePreferences:failed [object Object]
   "updatePreferences:failed"
   {
      [functions]: ,
      __proto__: { },
      config: { },
      data: { },
      status: 422,
      statusText: "Unprocessable Entity"
   }

Metadata Promise chain success [object Object]
   "Metadata Promise chain success"
   [
      0: { },
      length: 1
   ]

AnnotationEditor:modelUpdated: 141699 false
AnnotationEditor:modelUpdatesDrawabox: 141699
AnnotationEditor:modelUpdated: 149356 false
AnnotationEditor:modelUpdatesDrawabox: 149356
AnnotationEditor:modelUpdated: 149358 false
AnnotationEditor:modelUpdatesDrawabox: 149358
AnnotationEditor:modelUpdated: 149359 false
AnnotationEditor:modelUpdatesDrawabox: 149359
AnnotationEditor:modelUpdated: 149360 false
AnnotationEditor:modelUpdatesDrawabox: 149360
No temporary CSRF token has been found!

**Comment by atruskie** [comment]
I edited your comment - don't paste full logs into a issue.

I'm reading through the log now

**Comment by atruskie** [comment]
It appears the audio element threw and error...

**Comment by atruskie** [comment]
Are you running compressed resources (is your JS minified?)

You need to put a breakpoint on this line: https://github.com/QutBioacoustics/baw-client/blob/5a3de5dd9937fba43d793a604308e84809da32db/src/components/directives/ngAudio.js#L179

Is there any errors in the network tab?

**Comment by alvinsw** [comment]
Yes I am running the minified version.
No errors in network tab.
This will be hard to find out, I just tested it on my home machine, and it works there!
Probably caused by some privacy or security settings in IE?

**Comment by atruskie** [comment]
Okay so your next step is to reproduce this bug with unminified resources (i.e. in a debug environment). Its going to be hard to investigate further.

@cofiem suggested fiddling with security and privacy settings as well.

Additionally, try unhiding the native audio UI (do this in the dev tools console: `document.querySelector("audio").style.display = "block"`) and see if hitting the play button there works.

**Comment by alvinsw** [comment]
Unhiding the native audio UI just reveals the error:
![image](https://cloud.githubusercontent.com/assets/2344573/6224023/85066098-b6c0-11e4-8017-e76da295b3b5.png)

**Comment by atruskie** [comment]
This is very telling. This means it is probably not a bug that is our fault. Now why was the "audio playback aborted"?

**Comment by atruskie** [comment]
This http://www.reddit.com/r/webdev/comments/2blzh8/group_policy_blocking_html5_audio_in_ie/

says to check this: http://imgur.com/4GTrw4D

**Comment by alvinsw** [comment]
Thanks, that is spot on. Ticking the option `Play sounds in webpages` works for me. This issue is closed for now.
