### ISSUE TITLE
fix(visualization) Clicking/touching a tile can sometimes redirect to missing data

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-client#185]
Currently, the click resolution in the visualization strip is 60px - the same size as the image tiles - which means a click essentially represents clicking somewhere in that 60mins.

Current behaviour is to index into start of hour long block.

This behaviour can lead to faulty redirects - particularly at edge cases like:
 - negatively indexing into an audio file
 - indexing past the end of an audio file

It leads users to pages with no audio and no error message - very bad.

Present suggested solution is to smartly index into where we know there is data and then rely on (a yet to be) enhanced navigation bar in listen interface for fine grained navigation.

This will be sufficient for most cases, however for cases where:
 - two sample-style recordings occur in the same hour long block
 - or where two larger recordings end and start respectively in the same block

which recording do we navigate to?

Suggested solution means that there would be essentially some files we could never navigate to. Opinions @jwim1, @cofiem ?

**Comment by cofiem** [comment]
I think in here somewhere is the need to be able to go to the 'next' recording from the listen page. Exactly what 'next' means is not clear - perhaps prev and next in terms of audio recordings could be chronological order of recordings in the site (which would be transparent to the user - they wouldn't know it was a different recording)?

**Comment by atruskie** [comment]
yeah that's along what I was thinking - particularly the new enhanced nav bar on the listen page would show 24 hours around your current position, at the current site only... which allow a pundit to skip recordings

**Comment by cofiem** [comment]
An enhanced fine-grained nav UI is definitely needed. i'm not sure what form this would take, but it could be as simple as pre-populated drop-downs or locking on to particular points in the dragable bar to aid in understanding the half minute segments available.

**Comment by atruskie** [comment]
well i was thinking of simple resuing the distributionOverview - it is adequate and already made

**Comment by cofiem** [comment]
:+1: to between 1 minute and 24 hours around current location at current site only.
reuse of distribution overview sounds like a great idea :smiling_imp:
