### ISSUE TITLE
feat(visualize) Allow navigating back to your 'spot'

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-client#188]
The visualize page allows a user to navigate away from that page to listen to audio.

When navigate back their zoomed/panned position is lost - that is annoying.

Suggested to encode zoom and pan offsets into URL - probably best to do at all times

**Comment by cofiem** [comment]
Add a link on the listen page to the visualisation page. This could just specify the `siteId`. It could also link to a specific position on the visualisation page that corresponds with the current view of the listen page.

**Comment by atruskie** [comment]
Closed in #246 and 52a84aa8af99a576deef0a248fc91c89c92890a9
