### ISSUE TITLE
Update annotation library to new API

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-client#190]
The server API has been forced to update the API for the annotation library page.

We need to update the client so it uses the correct endpoints -- preferably the new API format.

*This issue is currently blocking a production deploy*

See:
 - https://github.com/QutBioacoustics/baw-server/issues/128
 - https://github.com/QutBioacoustics/baw-server/issues/176
 - https://github.com/QutBioacoustics/baw-server/commit/5227bf93d6bb97b4a496dc3fb669860291f00df4
 - https://github.com/QutBioacoustics/baw-server/issues/181
 - https://travis-ci.org/QutBioacoustics/baw-server/builds/54456750

**Comment by cofiem** [comment]
The blocking issues are now closed and deployed to staging. This includes
 - QutBioacoustics/baw-server#181
 - QutBioacoustics/baw-server#176
 - QutBioacoustics/baw-server#170
 - QutBioacoustics/baw-server#169

QutBioacoustics/baw-server#128 is the tracking issue for baw-server.

The library api endpoints have been removed.

**Comment by cofiem** [comment]
Filter options needed (these might be documented somewhere else, I couldn't find it):
 - ProjectId(s) (for links from other pages)
 - siteId(s) (for links from other pages)
 - partial tag(s)
 - date/time (window or start & end?)
 - 'find by similar' that just sorts on annotation duration

Needs to be linkable using QSP for all the filter options.
