### ISSUE TITLE
Calculated start offset values href visualization tiles is not being calculated correctly.

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-client#217]
See hrefs for http://staging.ecosounds.org/visualize?projectId=628

initial DX indicates just the first offset is wrong but it then jumps correctly.

Also check offsets used for navigating, particularly at the end of audio blocks.

**Comment by atruskie** [comment]
So at least some of this bug is expected behaviour.

For the bimblebox site, the first tile (remember tiles are aligned to absolute hour blocks of the day) starts at 18:00. The recording itself starts at 18:13 (815s diff). If we were to jump the user in at the start of the tile, we'd get an indexing error (i.e. equiv. to seeking to -815 seconds). This also explains why the second tile is offset such a weird amount: 3600 - 815 = 2785 (i.e. 2785 seconds is the number of seconds we have to seek into the recording until we line up with an absolute hour of the day).

This is the so called "smart click" functionality - we try and put the user in the spot that makes the most sense. Jumps like these will be less obscure when visualization tile images are shown as the norm... then you can quite clearly see where audio is and is not.

The spoken bug report involved the apparent discrepancy between the times clicked on for the other tiles (not the first) and the datetimes on the listen page. It turns out the date times on the listen page are all correct too. The time under the spectrogram, the spectrogram axis, and the time labels either side of the spectrogram are all accurate. However, the confusing label is the `Navigate to` label. It shows a weird offset. That is because that navigation control was designed to align to the start of the recording... not absolute time. So for a recording that started with a weird offset (like 35s into the minute), the navigate to label will always show multiple of 30s of that initial 35s. 

The last tiles for all three sites shown also behave as expected. Can't reproduce any end segment bugs.

While all of the above is potentially bad UI none of it is broken. @cofiem please discuss.

**Comment by cofiem** [comment]
:+1:
