### ISSUE TITLE
Visualize page - UI enhancements

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-client#221]
Suggested by @JessCappadonna

There's various tweaks that could be made to this page to make it more user friendly.

We need to add:

 - A bootstrap guide (hints / popup instructions on first use)
 - To tighten up the language
   - Rephrase 'Audio distribution' in header
   - Possibly remove 'False colour' phrasing in lower header
 - add easier to interpret dates to the time axis (not sure on best choice)
   - including site-wide consistency of date times (e.g. should not be AM/PM times)
 - add visual indicators to components that make it clear what their function is (i.e. click/drag or zoom)
 - fix visual cues (like borders, spacing, colors)  that users find confusing.

We need more clarification on most of these points. Please discuss, @jwim1, @JessCappadonna, @cofiem .

**Comment by cofiem** [comment]
This is all somewhat subjective, as there are few apps to compare. We're pretty much forging new ground here. Perhaps some comparisons with MS Word or even mobile device drawing apps might be useful?

**Comment by atruskie** [comment]
Yes and no.

Interface design is an old trade. This is not research. Just about layout and not confusing people.
Mainly I think we need someone competent to do it/give feedback (i.e. not me)

**Comment by atruskie** [comment]
Mostly closed with new UI updates from #246 .

Open new issues with more specific points for further work.
