### ISSUE TITLE
Visualize page

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-client#231]
Suggested by @YvonneP

Add axis labels to visualize charts (e.g. frequency / time)

**Comment by cofiem** [comment]
Also, I lose track of the date when there are no green tiles showing the date. Maybe add the date to the "Go to <time>' link?

**Comment by atruskie** [comment]
Fixed in https://github.com/QutBioacoustics/baw-client/commit/ae1daa6155429e07efff7cb3624e5d21e728830a
