### ISSUE TITLE
Add option to hide annotations on listen page

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-client#232]
The option to hide annotations, particularly using a QSP, will allow experiment designers to send multiple people to a segment of audio (on the listen page) and have them annotate the species there, without biasing them with existing annotations.

This could be useful for a number of different people (including Scott)

**Comment by cofiem** [comment]
:+1:

**Comment by atruskie** [comment]
Deadline: 20150914
Latest: 20150918
