### ISSUE TITLE
Footer CSS bug

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-client#234]
Footer overlaps content when the window is small or the content is larger than the window

**Comment by cofiem** [comment]
Also potential issue with float & absolute positioning?

**Comment by atruskie** [comment]
Pretty sure that's the regression https://github.com/QutBioacoustics/baw-client/commit/a381b5e6aba06a4a16a5766887aec34b569134f5#diff-c8e812ad7b7b83c99f1d3f9d2e38b5aaR17
