### ISSUE TITLE
Standardize secondary navigation

### ISSUE THREAD

**Issue by JessCappadonna** [QutBioacoustics/baw-client#260]
The secondary navigation can be confusing. The main confusion from the links on the left stems from two parts: a) they change and disappear based on context and b) they mix actions with navigation. By removing all actions from the left navigation it will largely be able to remain the same despite the current context. Actions (like _edit_, _new_, _delete_, etc...) will move into the right hand column.

All links on the left will be global unless descending into a hierarchy, in which case contextual navigation links will be shown in groups. Icons will also be added to the left menu.

    New navigation (left) menu:
    - (home) Home
    - (sign-in) Login / (user) My Profile 
    - (user-plus) Register / (square-o) My Annotations
    - (globe) Projects 
    - (server) Audio Analysis
    - (book) Library
    - (table) Data Request
    - (envelope) Send Audio
    - (bug) Report Problem
    - (line-chart) Website Statistics

	Other icons for standard use:
	- (bar-chart) visualize (project & site) [new name: _Data Visualisation_]
	- (tag) tags
	- (square-o) annotations
	- (play) Only used when immediate audio is played 
	- (headphones) Any link that takes to a listen page and must have text to say "listen"
	- (map-marker) sites
	- (download) Download 

Related [QutBioacoustics/baw-server/issues/275] - should be released at the same time.

**Comment by atruskie** [comment]
The bulk of the work has been done in the client. Closing and moving on but more tweaks are likely needed - file issues if that is the case.

Also, this commit is asymmetrical, the equivalent work has not been done in baw-server!
