### ISSUE TITLE
Library audio element not shown in firefox

### ISSUE THREAD

**Issue by peichins** [QutBioacoustics/baw-client#285]
https://www.ecosounds.org/library/262863/audio_events/214506
- affects both library page and library item page
- affects firefox mac. Not sure about windows
- audio element appears (play button etc) then disappears. May be caused by zero height. 

![image](https://cloud.githubusercontent.com/assets/5986336/21207175/560e708c-c2b2-11e6-8a3c-1cec1ab6a1e6.png)

**Comment by atruskie** [comment]
Confirmed for Firefox Windows as well.

The console output provides a hint... it looks like the mime-type binding is not working for some reason.

https://gyazo.com/5a559490abbd2e76d29a72fedbdf1783
