### ISSUE TITLE
Styling audio controls so they don't overlap the spectrogram on mobile

### ISSUE THREAD

**Issue by peichins** [QutBioacoustics/baw-client#314]
![image](https://user-images.githubusercontent.com/5986336/26860493-8c368642-4b81-11e7-8c98-06b20ae20e6c.png)

/citsci/bristlebird/listen
This occurs on android (chrome). Have not tested iPhone.

**Comment by atruskie** [comment]
Maybe this issue would be better resolved by componentizing the listen page controls? Address the cause rather than the symptom?
